nav:
  # 导航栏 Logo 图片
  logo:
  # 是否显示标题
  display_title: true
  # 是否固定导航栏
  fixed: true

menu:
  分类: /categories
  标签: /tags
  友情链接: /links

code_blocks:
  theme: pale night
  macStyle: true
  height_limit: false
  word_wrap: false

  copy: true
  language: true
  shrink: false
  fullpage: true

disable_top_img: false
index_img: https://zhengyu-personal-blog.oss-rg-china-mainland.aliyuncs.com/%E7%94%98%E9%9B%A8.jpg

cover:
  index_enable: true
  aside_enable: true
  archives_enable: true
  default_cover:

post_meta:
  page:
    date_type: created
    date_format: date
    categories: true
    tags: true
    label: true
  post:
    position: left
    date_type: both
    date_format: date
    categories: true
    tags: true
    label: true

post_copyright:
  enable: true
  decode: true
  author_href:
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

footer:
  owner:
    enable: true
    since: 2025
  custom_text: 欢迎来到我的博客
  copyright: true

aside:
  position: left
  card_announcement:
    enable: false
  card_recent_post:
    enable: false
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-zhihu
      text: Follow Me
      link: https://www.zhihu.com/people/jqk-61

rightside_scroll_percent: true

wordcount:
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true

share:
  use:

lightbox: fancybox

favicon: /img/favicon.ico

avatar:
  img: /img/butterfly-icon.png
  effect: false